### PR TITLE
Update Entity Account ID Routes

### PR DESCRIPTION
**Pull request by pk556**
- Established logic for EntityService system that will be used for other routes
- Created interface for server so that EntityServices can have access to it and 'makeRequest' functionality
- 'makeFunctionality' -> 'MakeFunctionality' so that services using server interface can have access to this to make requests to bluecat
- Implemented logic about for GET route for Entity account ID route

### CODE REVIEW

**Comment by pk556** [comment]
## Before Testing
**You must be on the following VPN to access the Bluecat Test Database:  labvpn.its.yale.edu**

Config needs to be updated to the following format:
```json
{ 
  "listenAddress": ":3082",
  "proxyBackend": {
    "baseUrl": "https://api-tst.internal.yale.edu",
    "backendPrefix": "/v1/dns",
    "token": "{{ token }}"
  },
  "bluecat": {
    "account": "bam-test",
    "baseUrl": "https://10.16.8.40/Services/REST/v1",
    "username": "{{ READWRITE_USERNAME }}",
    "password": "{{ READWRITE_PASSWORD }}"
  },
  "token": "{{ token }}",
  "logLevel": "info",
  "org": "dev"
}
```

**Comment by pk556** [comment]
## Testing Middleware

To test the middleware, play around with values for {account} in the GET route below. Only ‘bam-test’ should pass through.

If no value is passed (such as hitting /{id} instead of /{account}/{id}, then it should not hit the middleware at all.

Wrong values should return “invalid account”.

**Comment by pk556** [comment]
## Testing GET /{account}/{id}

1. You first need to retrieve object IDs to use to test the route
    a. You can use the following example IDs:
        i. 3610146 – “Spinup Testing” IPv4 Block
        ii. 100882 – Configuration ID
        iii. 2 – Proteus Entity Type without a properties field
        iiii. 1 – Entity Doesn't Exist
    b. Or you can use [GET /v1/searchByObjectTypes](https://docs.bluecatnetworks.com/r/Address-Manager-API-Guide/GET/v1/searchByObjectTypes/9.4.0) using your own code to search for a specific object that will return an ID along with it
    i. Use the following parameters
```
params={
        'keyword': {{ keyword }}, // such as 10.5.0.2
        'types': {{ keyword_type }}, // such as IP4Address
        'start': 0,
        'count': 10,
        'includeHA': False
    },
```
    
c. Or you can use random IDs
2. Once you have an id, you can substitute it into the following route: `http://localhost:3082/v2/dns/bam-test/id/{id}`
 

Things to test for:
- Successfully retrieving object information from ID
- Sending back entity not found if an entity doesn’t exist
- Not returning an error if properties or name are null in the returned entity

**Comment by pk556** [comment]
## Testing DELETE /{account}/id/{id}

1. The best way to test this route is to probably try it on the following types. The delete route should only work on the following types but nothing else:
- HostRecord
- ExternalHostRecord
- AliasRecord
- IP4Address
- MACAddress
- MACPool

2. Go to [10.16.8.40](http://10.16.8.40/app), login, and try creating one of the objects above.
    a. For example, you could go to IP Space → 10.0.0.0/8 → 10.5.0.0/16 → 10.5.0.0/26
    b. Try assigning an IP address here
    c. Use [GET /v1/searchByObjectTypes](https://docs.bluecatnetworks.com/r/Address-Manager-API-Guide/GET/v1/searchByObjectTypes/9.4.0) using your own code to retrieve the ID of the IP4Address that you created
        i. Use the following parameters 
```
params={
        'keyword': {{ keyword }}, // such as 10.5.0.2
        'types': {{ keyword_type }}, // such as IP4Address
        'start': 0,
        'count': 10,
        'includeHA': False
    },
```
3. Use Delete route to delete the object: http://localhost:3082/v2/dns/bam-test/id/{id}

 

Things to test for:
- Successful deletion of an ‘allowed-to-be-deleted’ entity such as IP4Address
- Refusal of deletion for an entity that is not on the allowed list
- If entity is not found or doesn’t exist, return Entity not found error

**Comment by pk556** [comment]
## Notable Changes in this PR
- Restructured files
    - Created an internal folder under dns-api-go and moved most files under there (such as common, api, etc.)
- Services
    - Created Base entity service that manages GET and DELETE logic for an entity
    - Created tests for this service
    - Entity model that gets returned by service
    - Custom errors for service
 - New middleware
    - Added middleware for validating account, which will be used by all routes with /{account}
    - Created tests for this
    - Added subrouter that uses this middleware
 - Logging
    - New logging uses zap
    - Changed logging calls for all files under internal except for server.go, config.go, and session.go
 - Server
    -  Created a server interface for mocking that is under interfaces folder
 - Created mocks folder for mocking
 - Handlers
    - New handler for GET route described above
    - New handler for DELETE route described above
    - Did not finish tests for these

**Comment by btassone** [comment]
* https://github.com/YaleSpinup/dns-api-go/tree/pk556-update-account-id-routes/sts
We can remove this folder as we aren't doing any assuming of aws roles

**Comment by btassone** [comment]
LGTM :shipit:

**Review by btassone — APPROVED** [review]

**Pull request merged**
