### PR TITLE
Add Zone Service

### PR DESCRIPTION
**Pull request by pk556**
# Testing this PR

## Testing the Zone Service Routes

To ensure the new Zone Service routes are functioning correctly, follow these steps to test each route. Be aware of potential edge cases and ensure comprehensive coverage.

### Testing `GET /:account/zones`

**Purpose:** Retrieve a list of zone entities.

**Steps:**
1. **Basic Request:**
   - Send a GET request to `/:account/zones`.
   - Verify that the response status is `200 OK`.
   - Check that the response body contains a JSON array of zone entities.

2. **Parameter Testing:**
   - Test with different `offset` and `limit` values in the query parameters.
   - Example: `GET /:account/zones?offset=0&limit=5`.
   - Verify that the response contains the correct number of entities based on the `limit`.
   - **Note:** The maximum value for `limit` is 10.

3. **Hint Parameter:**
   - Test with the `hint` parameter to filter results.
   - Example: `GET /:account/zones?hint=yale`.
   - Verify that the response contains entities matching the hint criteria.
   - **Note:** The `hint` cannot contain spaces.
   - **Explanation:** The `hint` is typically a string that can represent a partial or complete domain name. The API will return zones that match the hint either fully or partially.

4. **Invalid Parameters:**
   - Test with invalid `offset` and `limit` values (e.g., negative numbers, non-integer values).
   - Verify that the response status is `400 Bad Request` and contains an appropriate error message.

5. **Edge Cases:**
   - Test with `offset` and `limit` values that exceed the total number of available entities.
   - Verify that the response is handled gracefully and does not cause errors.

### Testing `GET /:account/zones/:id`

**Purpose:** Retrieve a specific zone entity by its ID.

**Steps:**
1. **Basic Request:**
   - Send a GET request to `/:account/zones/:id` with a valid zone ID.
   - Verify that the response status is `200 OK`.
   - Check that the response body contains the correct zone entity in JSON format.

2. **Invalid ID:**
   - Test with an invalid zone ID (e.g., non-existent ID, non-integer value).
   - Verify that the response status is `404 Not Found` or `400 Bad Request` with an appropriate error message.

3. **Type Mismatch:**
   - Ensure that the `GetEntity` method correctly identifies the entity type.
   - Test with an ID that does not correspond to a zone entity.
   - Verify that the response status is `400 Bad Request` and contains an `ErrEntityTypeMismatch` error message.

4. **Edge Cases:**
   - Test with boundary values for the zone ID (e.g., minimum and maximum possible integer values).
   - Verify that the service handles these cases without errors.
   
## Testing Other Routes
   
I made minor edits to the other basic routes in the shared dev branch, so please test these routes again to ensure they are functioning correctly. The routes to test in handlers.go are:
- `GET /ping`
- `GET /version`
- `GET /systeminfo`

### CODE REVIEW

**Comment by pk556** [comment]
### Summary of Changes in Shared Dev Branch

## Entity Management Enhancements

- Added `GetEntities` function:
    - Purpose: Retrieves a list of entities from the Bluecat API.
    - Features:
        - Filtering by entityType.
        - Pagination support through start and count parameters.
    - Parameters:
        - start: Starting index for pagination.
        - count: Number of entities to retrieve.
        - parentId: ID of the parent entity to filter by.
        - entityType: Type of entities to retrieve.
        - includeHA: Whether to include High Availability entities.
    - Usage example: Can be used to get the containerID needed in some services and functions.
- Added tests for `GetEntities`.
- Added mock for `GetEntities` in mock base service.
- Added new error `ErrEntityTypeMismatch`:
    - Purpose: Indicates that the type of the entity being deleted does not match any of the expected types.
    - Benefits:
        - Provides clear and specific error for type mismatches.
        - Aids in debugging issues related to entity type mismatches during deletion.
- Updated `DeleteEntity` to include a new parameter for type checking:
    - New parameter: `expectedTypes`
    - Purpose:
        - Type Validation: Ensures only entities of specified types can be deleted.
        - Safety: Prevents accidental deletion of entities that don't match expected types.
    - By default, DeleteEntity checks if the entity is deletable according to its type, but you can pass in expectedTypes to be more specific.

## Entity Response Improvements

- Added tests for `IsEmpty` for `EntityResponse`.
- Separated `EntityResponse` logic:
    - Purpose: Improves code organization and maintainability.
    - Features of `EntityResponse`:
        - Representation: Represents raw response from the Bluecat API.
        - Conversion: Provides methods to convert raw response into a usable `Entity` object.
        - Validation: Includes methods to check if the response is empty (no entity found).

## Handler and Routing Enhancements

- Created a common handler (`HandleGetEntityReq`) for GET requests to retrieve entities.
- Updated GET service entity handlers to use the common handler.
- Created `helpers.go` file for API utilities, including a `respond` function.
- Updated all routes to use the new `respond` function (e.g., `pingHandler`, `versionHandler`).

## Testing and Mocking Enhancements

- Fixed tests to expect responses formatted by `Encoder` for various handlers.
- Updated `mock_entity_service.go`.

## Common Utilities and Helpers

- Moved common API functions to `helpers.go` (e.g., `MakeRequest`, `generateAuthToken`, `handleError`).
- Added `Contains` function to `common/helpers.go` to check if a string is in a string slice.

## Naming and Structural Updates

- Updated naming conventions for `EntityGetter` and `EntityDeleter`, including renaming related tests.
- Added `types.go` file to define Bluecat types as constants.

**Comment by pk556** [comment]
image

## Explanation of Service Architecture

The service architecture in this project is designed to promote code reuse and maintainability by leveraging a BaseEntityService that provides foundational methods: GetEntity, DeleteEntity, and GetEntities. These methods serve as the building blocks for more specialized services. For instance, a specialized service like ZoneService extends the functionality of BaseEntityService by incorporating its own GetEntity method. This method calls the GetEntity from BaseEntityService and performs additional checks specific to the service's requirements. Similarly, specialized services may have other methods that utilize GetEntities from BaseEntityService to obtain necessary data for making specific API requests. This layered approach allows each service to inherit common functionality while also implementing unique methods tailored to their specific requirements.

**Comment by pk556** [comment]
## Example Flow of Incoming Request That Needs to Retrieve an Entity

This flow diagram illustrates how an incoming request that needs to retrieve an entity is processed. The router directs the request to the appropriate handler based on the URL route. The diagram highlights how different handlers can utilize a common handler function, HandleGetEntityReq, to centralize logic, reduce code duplication, and maintain consistency across the application.

image

**Comment by pk556** [comment]
# Testing this PR

## Testing the Zone Service Routes

To ensure the new Zone Service routes are functioning correctly, follow these steps to test each route. Be aware of potential edge cases and ensure comprehensive coverage.

### Testing `GET /:account/zones`

**Purpose:** Retrieve a list of zone entities.

**Steps:**
1. **Basic Request:**
   - Send a GET request to `/:account/zones`.
   - Verify that the response status is `200 OK`.
   - Check that the response body contains a JSON array of zone entities.

2. **Parameter Testing:**
   - Test with different `offset` and `limit` values in the query parameters.
   - Example: `GET /:account/zones?offset=0&limit=5`.
   - Verify that the response contains the correct number of entities based on the `limit`.
   - **Note:** The maximum value for `limit` is 10.

3. **Hint Parameter:**
   - Test with the `hint` parameter to filter results.
   - Example: `GET /:account/zones?hint=yale`.
   - Verify that the response contains entities matching the hint criteria.
   - **Note:** The `hint` cannot contain spaces.
   - **Explanation:** The `hint` is typically a string that can represent a partial or complete domain name. The API will return zones that match the hint either fully or partially.

4. **Invalid Parameters:**
   - Test with invalid `offset` and `limit` values (e.g., negative numbers, non-integer values).
   - Verify that the response status is `400 Bad Request` and contains an appropriate error message.

5. **Edge Cases:**
   - Test with `offset` and `limit` values that exceed the total number of available entities.
   - Verify that the response is handled gracefully and does not cause errors.

### Testing `GET /:account/zones/:id`

**Purpose:** Retrieve a specific zone entity by its ID.

**Steps:**
1. **Basic Request:**
   - Send a GET request to `/:account/zones/:id` with a valid zone ID.
   - Verify that the response status is `200 OK`.
   - Check that the response body contains the correct zone entity in JSON format.

2. **Invalid ID:**
   - Test with an invalid zone ID (e.g., non-existent ID, non-integer value).
   - Verify that the response status is `404 Not Found` or `400 Bad Request` with an appropriate error message.

3. **Type Mismatch:**
   - Ensure that the `GetEntity` method correctly identifies the entity type.
   - Test with an ID that does not correspond to a zone entity.
   - Verify that the response status is `400 Bad Request` and contains an `ErrEntityTypeMismatch` error message.

4. **Edge Cases:**
   - Test with boundary values for the zone ID (e.g., minimum and maximum possible integer values).
   - Verify that the service handles these cases without errors.
   
## Testing Other Routes
   
I made minor edits to the other basic routes in the shared dev branch, so please test these routes again to ensure they are functioning correctly. The routes to test in handlers.go are:
- `GET /ping`
- `GET /version`
- `GET /systeminfo`

**Review by trstne — APPROVED** [review]
Tested the zone service, works as intended (sorry for the delay).

**Review by btassone — APPROVED** [review]
Tested and can confirm routes work as intended. Approved

**Pull request merged**
